name: Release
# Build and attach supported artifacts a draft release tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get tags to allow build script to get build version

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit Test
        run: make unit_test

      - name: Build
        run: |
          make build_amd
          make build_arm

      - name: Package
        run: |
          make package_amd
          make package_arm

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            target/scanoss-go-api-linux-amd64
            target/scanoss-go-api-linux-arm64
            scanoss-go_linux-amd64_${{ github.ref_name }}-1.tgz
            scanoss-go_linux-arm64_${{ github.ref_name }}-1.tgz
